version: '3'

services:
  at-at:
    container_name: at-at
    build:
      context: ./at-at
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    depends_on:
      - 'server'
    volumes:
      - './at-at:/app'
      - '/app/node_modules'
    environment: 
      - CHOKIDAR_USEPOLLING=true
  
  server:
    build: server
    ports:
      - '3001:3001'
    depends_on:
      - 'database'

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=at_at
      - POSTGRES_USER=akbar
      - POSTGRES_PASSWORD=itsATrap
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql